_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.18.3
            "8":
                - 1
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 32
clip_epsilon:
    value: 0.2
ent_coef:
    value: 0.01
gamma:
    value: 0.99
hidden_sizes:
    value:
        - 64
        - 64
        - 64
lam:
    value: 0.95
learning_rate:
    value: 0.001
max_grad_norm:
    value: 0.5
max_steps:
    value: 64
n_envs:
    value: 32
num_episodes_to_avg:
    value: 23
num_returns_to_avg:
    value: 3
total_timesteps:
    value: 30000
update_epochs:
    value: 2
