_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.18.3
            "8":
                - 1
                - 5
            "12": 0.18.3
            "13": linux-x86_64
criterion_episodes:
    value: 5
epsilon:
    value: 1
epsilon_update:
    value: 1500000
gamma:
    value: 0.99
hidden_sizes:
    value:
        - 128
        - 128
learning_rate:
    value: 0.001
max_steps_per_episode:
    value: 18000
min_epsilon:
    value: 0.01
minibatch_size:
    value: 32
num_episodes:
    value: 700
rep_omega:
    value: 0.2
replay_size:
    value: 50000
target_update_freq:
    value: 1000
tau:
    value: 0.1
